services:
  - type: web
    name: DekkBakendi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600 --workers 1
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 600 --workers 1"
      - key: DATABASE_URL
        sync: false

  - type: cron
    name: daily-scrape
    runtime: python
    schedule: "0 0 * * *"  # Run at midnight every day
    buildCommand: pip install -r requirements.txt
    startCommand: python Leita/run_all.py
