services:
  - type: web
    name: DekkBakendi
    runtime: python
    buildCommand: pip install -r requirements.txt && python deploy_setup.py && pip install -e .
    startCommand: python copy_spiders.py && gunicorn app:app --timeout 600 --workers 1
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 600 --workers 1"
      - key: DATABASE_URL
        sync: false

  - type: cron
    name: daily-scrape
    runtime: python
    schedule: "0 0 * * *"
    buildCommand: pip install -r requirements.txt && python deploy_setup.py && pip install -e .
    startCommand: python copy_spiders.py && python Leita/run_all.py
